spring:
  datasource:
    aa:
      jdbcUrl: jdbc:mysql://192.168.33.10:3306/aa?useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver