spring:
  datasource:
    aaro:
      url: jdbc:mysql://192.168.33.10:3306/aa?useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qiye.163.com
    prot: 994
    username: no-repay@tuotiansudai.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.qiye.163.com
logging:
  level:
    com:
      tuotiansudai:
        diagnosis: debug
  path: /var/log/ttsd-diagnosis

diagnosis:
  schedule:
    hour: 2
    minute: 18
  report:
    notify-mail-from: no-repay@tuotiansudai.com
    notify-mail-address: dev@tuotiansudai.com
    notify-mail-address-qa: dev@tuotiansudai.com
